apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:8.2.2
          imagePullPolicy: IfNotPresent
#          volumeMounts:
#            - name: grafana-datasources
#              mountPath: /etc/grafana/provisioning/datasources
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
#      volumes:
#      - name: grafana-datasources
#        secret:
#          secretName: grafana-datasources
#          defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
    - port: 3000
      protocol: TCP
      name: grafana
      targetPort: 3000
      nodePort: 32500
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: grafana-datasources
#  namespace: monitoring
#type: Opaque
#stringData:
#  datasources.yaml: |
#    datasources:
#    - name: loki
#      type: loki
#      access: proxy
#      # url: http://loki.monitoring.svc:3100
